### PR TITLE
Type safe API (working preview)

### PR DESCRIPTION
**Pull request by Thomaash**
This is a part of my effort to make the DataSet and DataView fully type safe for use in TypeScript projects.

# The old API
At the moment the type and fields parameters are ignored as if missing, which leads to the fact, that the returned type doesn't correspond to the returned data if some of these parameters are passed. I originally planned to fix the types of the old API, but it turned out to be surprisingly deep and branched rabbit hole and I rather abandoned this idea. If everything worked out the get method would need whopping 78 overloads to work correctly (it already has 13), however I couldn't make it work at all. The nested generic types just don't work with type inference, it would be necessary to call it like get<T1, T2, T3>(...args). Atop of that the types would be really difficult to navigate (looking for the correct overload out of 78 overload with complex, highly generic parameters?) and error prone (keeping this whole thing in sync between DataView, DataSet and DataInterface would be a lot of work, TS would check something, but not everything).

Another problem (also addressed by this pull request) is the update method, which can introduce partial items even though the type disallow it. For type safety there should be alternative update method that disallows adding of missing items to ensure that partial items can't slip by without the compiler complaining and are used only for updating existing items.

# UpdateOnly (done)
Type safe counterpart to the old update method. It doesn't allow new items to be created (add has to be used explicitly), therefore there is no risk of partial items slipping by. Add and remove are type safe already, so no need for change there.

# Streams API (working preview)
This is the replacement for distinct, forEach, get (partially), getIds, map, max and min (the old API is kept intact for backwards compatibility). It's very flexible, type safe and most importantly, everything implemented in DataSet immediately works in DataView (the DV just gets the stream from the DS for it's ids).

## Advantages
- Flexible:
```javascript
exampleItem = {
  id: 3,
  valid: true,
  payload: {
    values: [],
  },
}

const countOfValidItemsWithPayloadValues = dataSet.stream()
  .filter((item, id) => item.valid) // filtered using some condition
  .map((item, id) => item.payload) // mapped using custom mapping function
  .filter((payload, id) => payload.values.length > 0) // can be filtered multiple times
  .reduce((acc, payload, id) => acc + 1, 0) // reduced into a single value
```
- Iterable:
```javascript
const array = [...dataView.stream()] // an array of DV items
for (const item of dataSet.stream().filter((item, id) => id % 2 === 0)) {
  // do something with the item
}
```
- Single implementation for both DataView and DataSet (potentially even other classes).
- Type safe.
- Doesn't conflict with the old API (not a breaking change).
- Yields up to date data on each iteration (change in DataSet appears in the next iteration of existing stream).
- Optionally can be cached to work with the same data multiple times.

## Disadvantages
- No easy way to forward the configuration around and then use it:
```javascript
const config = {
  filter: () => Math.random() < 0.5,
  order: 'id',
}

// somewhere else
const data = dataSet.get(options)

// if this is actually useful a (type unsafe) helper method could be created using config with the following structure:
const exampleStreamConfig = [
  ['filter', () => Math.random() < 0.5],
  ['order', 'id'],
]
```

### CODE REVIEW

**Comment by Thomaash** [comment]
@mojoaxel Any comments? Improvements? Questions?

**Comment by mojoaxel** [comment]
@Thomaash Thanks!
I think we need to wait a few more days for this! @yotamberk is currently merging the whole [timeline-plus](https://github.com/yotamberk/timeline-plus) in to our vis-timeline. After this is done we are ready for more big changes.
Lets than test your changes with all libs (graph3d, timeline, network) and see if everything still works. I try to have a look this week!

**Comment by mojoaxel** [comment]
npm gives me warnings:
```
npm WARN @typescript-eslint/eslint-plugin@1.12.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.12.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by Thomaash** [comment]
@mojoaxel I'll look at this tomorrow and open it for review (I want to add at least one more thing).

The @typescript-eslint warnings are an error in peer dependencies, it works just fine. There is merged pull request (3 days ago) on their repo, so it should disappear with the next update.

Regarding vis-configs my proposal is https://github.com/Thomaash/vis-configs , it basically contains the configs (ESLint, Prettier and Babel at the moment, but later we can include other things that repeat) and makes them available for import from other packages. There's readme with how tos, including a method how to exclude old files without changing them at all. It's tested and proved to work in vis-data. You can open an issue there or we can continue in https://github.com/visjs/vis-util/issues/4 .

**Comment by mojoaxel** [comment]
> @mojoaxel Any comments? Improvements? Questions?

Will the new API be compatible with the old one? There are multible projects already depending on this and I don't we should break the old API but adopt the different charts slowly to the new functions.

**Comment by Thomaash** [comment]
It's a minor change, it just adds new methods and keeps the old ones unchanged.

**Pull request merged**
