### PR TITLE
fix types for typescript 4.8

### PR DESCRIPTION
**Pull request by TimurUncountable**
Fixes https://github.com/visjs/vis-data/issues/985

### CODE REVIEW

**Comment by perepichai** [comment]
Hi @Thomaash, could you please check and accept this pr? Angular 15 has been released and it requires typescript 4.8. So now it is not possible to use vis-data and Angular 15 together. It would be great to fix types for typescript 4.8. Thanks

**Review by AdrienRedon — DISMISSED** [review]

**Comment by adam221821** [comment]
Hi, @Thomaash @AdrienRedon when is the release of changes planned?

**Review by adam221821 — DISMISSED** [review]

**Comment by mircotoepfer** [comment]
Can please someone jump in here for the additional review?

**Review by abhinandhanreddyk — DISMISSED** [review]

**Comment by mircotoepfer** [comment]
Hello,

how are you going with this change? How does the change get into a new version?

**Review by Thomaash — APPROVED** [review]
Thanks for your contribution

**Pull request merged**
